// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBNGiSJbl1barNh11Nd0K5Zu-UBDC0o9U',
    appId: '1:790706079370:web:095a240ba97a750421cf73',
    messagingSenderId: '790706079370',
    projectId: 'e-commerce-da651',
    authDomain: 'e-commerce-da651.firebaseapp.com',
    storageBucket: 'e-commerce-da651.appspot.com',
    measurementId: 'G-DLDM1CTPJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy14FyfdINSAHVgW-0vHRA9PkBKmE3-9s',
    appId: '1:790706079370:android:7dd6f0495182799f21cf73',
    messagingSenderId: '790706079370',
    projectId: 'e-commerce-da651',
    storageBucket: 'e-commerce-da651.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVCI18oUVW86EK6XpUxRgNBA5EFY0-5RQ',
    appId: '1:790706079370:ios:b5cccc2b40d8a7ef21cf73',
    messagingSenderId: '790706079370',
    projectId: 'e-commerce-da651',
    storageBucket: 'e-commerce-da651.appspot.com',
    iosBundleId: 'com.prodigi.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVCI18oUVW86EK6XpUxRgNBA5EFY0-5RQ',
    appId: '1:790706079370:ios:7b70b31b54366dfb21cf73',
    messagingSenderId: '790706079370',
    projectId: 'e-commerce-da651',
    storageBucket: 'e-commerce-da651.appspot.com',
    iosBundleId: 'com.prodigi.ecommerce.RunnerTests',
  );
}
